create table applicant_consents (status tinyint not null, applicant_id bigint not null, id bigint not null auto_increment, revoked_at datetime(6), signed_at datetime(6) not null, storage_url varchar(255), terms_version varchar(255), consent_type enum ('CONTACT','DATA_PROCESSING','MARKETING','MEDICAL','TERMS_AND_CONDITIONS','TRAVEL') not null, source enum ('OFFICE','PHONE','RECRUITMENT_DRIVE','WEBSITE'), primary key (id)) engine=InnoDB;
create table applicant_documents (is_current bit not null, version integer not null, applicant_id bigint not null, document_type_id bigint not null, file_asset_id bigint, id bigint not null auto_increment, uploaded_at datetime(6) not null, verified_at datetime(6), verified_by bigint, rejection_reason TEXT, status enum ('EXPIRED','NOT_SUBMITTED','REJECTED','RESUBMISSION_REQUIRED','UNDER_REVIEW','UPLOADED','VERIFIED') not null, primary key (id)) engine=InnoDB;
create table applicant_media (applicant_id bigint not null, file_asset_id bigint not null, id bigint not null auto_increment, uploaded_at datetime(6) not null, description TEXT, media_type enum ('AUDIO','OTHER','PHOTO','VIDEO') not null, primary key (id)) engine=InnoDB;
create table applicant_profiles (available_from date, number_of_children integer, preferred_salary decimal(38,2), willing_to_relocate bit not null, years_of_experience integer, applicant_id bigint not null, created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), current_employer varchar(255), current_position varchar(255), education_level varchar(255), employment_status varchar(255), field_of_study varchar(255), languages TEXT, next_of_kin_name varchar(255), next_of_kin_phone varchar(255), next_of_kin_relationship varchar(255), preferred_countries TEXT, preferred_job_categories TEXT, preferred_salary_currency varchar(255), professional_summary TEXT, reason_for_leaving TEXT, relevant_experience TEXT, religion varchar(255), skills TEXT, availability enum ('AVAILABLE_IMMEDIATELY','AVAILABLE_IN_30_DAYS','EMPLOYED','UNAVAILABLE'), marital_status enum ('DIVORCED','MARRIED','SINGLE','WIDOWED'), primary key (id)) engine=InnoDB;
create table applicant_timeline (applicant_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, performed_by bigint, description TEXT, metadata TEXT, event_type enum ('APPLICATION_STATUS_CHANGED','APPLICATION_SUBMITTED','BLACKLISTED','DEACTIVATED','DEPLOYED','DOCUMENT_REJECTED','DOCUMENT_UPLOADED','DOCUMENT_VERIFIED','ELIGIBLE','INTERVIEW_COMPLETED','INTERVIEW_SCHEDULED','LIFE_STAGE_CHANGED','OFFER_ACCEPTED','OFFER_MADE','OFFER_REJECTED','PLACEMENT_CREATED','PROFILE_COMPLETED','PROFILE_UPDATED','RECRUITER_ASSIGNED','REGISTERED','SUBMITTED_FOR_REVIEW','VETTED') not null, primary key (id)) engine=InnoDB;
create table applicants (age integer, current_salary float(53), date_of_birth date, dob date, elderly_care bit, extra_pay bit, has_cat bit, has_dog bit, live_out bit, older_than1 bit, private_room bit, special_needs bit, younger_than1 bit, approved_at datetime(6), approved_by_id bigint, assigned_recruiter_id bigint, created_at datetime(6), hired_at datetime(6), hired_by_id bigint, id bigint not null auto_increment, updated_at datetime(6), vetted_at datetime(6), vetted_by_id bigint, alternative_phone varchar(32), applicant_number varchar(32) unique, phone_number varchar(32) not null, address TEXT, county varchar(255), current_location varchar(255), current_profession varchar(255), email varchar(255), experience varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, middle_name varchar(255), nationality varchar(255), password_hash varchar(255), reference_number varchar(255), video_url varchar(255), applicant_type varchar(20), employment_status enum ('EMPLOYED','NOT_EMPLOYED'), gender enum ('FEMALE','MALE','OTHER'), job_interest enum ('INTERNATIONAL_JOBS','LOCAL_JOBS'), lifecycle_stage varchar(30), registration_source varchar(30), status varchar(20) not null, primary key (id)) engine=InnoDB;
create table application_languages (application_id bigint not null, languages enum ('ARABIC','ENGLISH','KISWAHILI')) engine=InnoDB;
create table audit_logs (changed_by bigint, entity_id bigint not null, id bigint not null auto_increment, timestamp datetime(6) not null, action varchar(255) not null, changed_by_name varchar(255), details TEXT, entity_type varchar(255) not null, primary key (id)) engine=InnoDB;
create table campaign_members (added_at datetime(6) not null, applicant_id bigint not null, campaign_id bigint not null, id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table campaigns (end_date date, start_date date, created_at datetime(6), created_by bigint, id bigint not null auto_increment, updated_at datetime(6), description TEXT, name varchar(255) not null, status enum ('ACTIVE','CANCELLED','COMPLETED','DRAFT','PAUSED') not null, target_applicant_type enum ('INTERNATIONAL','LOCAL'), primary key (id)) engine=InnoDB;
create table communication_logs (created_at datetime(6) not null, entity_id bigint not null, id bigint not null auto_increment, initiated_by bigint, contact_name varchar(255), entity_type varchar(255) not null, outcome TEXT, summary TEXT not null, channel enum ('EMAIL','IN_PERSON','PHONE','SMS','WHATSAPP') not null, direction enum ('INBOUND','OUTBOUND') not null, primary key (id)) engine=InnoDB;
create table contract_amendments (amendment_date datetime(6), approved_by bigint, contract_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, description TEXT not null, status enum ('APPROVED','PROPOSED','REJECTED') not null, primary key (id)) engine=InnoDB;
create table contracts (accommodation_provided bit not null, duration_months integer not null, end_date date, filled_positions integer not null, number_of_positions integer not null, renewable bit not null, salary decimal(38,2) not null, start_date date, transport_provided bit not null, created_at datetime(6), created_by bigint, employer_id bigint not null, id bigint not null auto_increment, updated_at datetime(6), benefits TEXT, country varchar(255) not null, currency varchar(255), job_category varchar(255) not null, notes TEXT, terms_and_conditions TEXT, working_hours varchar(255), status enum ('CLOSED','FILLED','OPEN') not null, primary key (id)) engine=InnoDB;
create table document_requirements (required bit not null, document_type_id bigint not null, id bigint not null auto_increment, opportunity_id bigint, applicant_type enum ('INTERNATIONAL','LOCAL') not null, primary key (id)) engine=InnoDB;
create table document_types (requires_verification bit not null, id bigint not null auto_increment, code varchar(40) not null, description TEXT, name varchar(255) not null, category enum ('CERTIFICATION','EMPLOYMENT','IDENTITY','MEDICAL','TRAVEL') not null, primary key (id)) engine=InnoDB;
create table employers (created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), address TEXT, company_name varchar(255) not null, contact_email varchar(255), contact_name varchar(255), contact_phone varchar(255), country varchar(255), notes TEXT, status enum ('ACTIVE','INACTIVE') not null, primary key (id)) engine=InnoDB;
create table file_assets (id bigint not null auto_increment, size_bytes bigint, uploaded_at datetime(6) not null, uploaded_by bigint, content_type varchar(255), file_url varchar(255) not null, original_name varchar(255) not null, stored_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table int_application_languages (inter_application_id bigint not null, languages enum ('ARABIC','ENGLISH','KISWAHILI')) engine=InnoDB;
create table inter_applicants (age integer, current_salary float(53), dob date, approved_at datetime(6), approved_by_id bigint, created_at datetime(6), hired_at datetime(6), hired_by_id bigint, id bigint not null auto_increment, updated_at datetime(6), vetted_at datetime(6), vetted_by_id bigint, current_location varchar(255), current_profession varchar(255), email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, middle_name varchar(255), nationality varchar(255), number_of_kids varchar(255), password_hash varchar(255), phone_number varchar(255), reference_number varchar(255), religion varchar(255), video_url varchar(255), education_level enum ('PRIMARY','SECONDARY','UNIVERSITY'), employment_status enum ('EMPLOYED','NOT_EMPLOYED'), job_recruitment enum ('ADMINISTRATIONS','AGRICULTURE','CAREGIVING','CLEANING','CONSTRUCTIONS','DOMESTIC_WORKERS','EDUCATION','ELECTRICIANS','GARMENTS','HEAVY_EQUIPMENT','HOTEL_HOSPITALITY','MANUFACTURING','MECHANICAL','MEDICAL','POWER_GAS_WATER','SECURITY','SUPERMARKETS','TECHNOLOGY'), marital_status enum ('MARRIED','SINGLE'), status enum ('APPROVED','ASSIGNED','DOCUMENT_VERIFICATION','DRAFT','HIRED','INTERVIEW','PENDING','PLACED','RECRUITMENT_REVIEW','REJECTED','SUBMITTED','VETTED'), primary key (id)) engine=InnoDB;
create table interviews (rating integer, application_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, interviewer_id bigint, scheduled_at datetime(6) not null, location varchar(255), meeting_link varchar(255), notes TEXT, outcome enum ('FAIL','NO_DECISION','PASS','PENDING'), status enum ('CANCELLED','COMPLETED','MISSED','RESCHEDULED','SCHEDULED') not null, type enum ('EMPLOYER_INTERVIEW','SSL_SCREENING') not null, primary key (id)) engine=InnoDB;
create table media_files (expiry_date date, application_id bigint, id bigint not null auto_increment, inter_application_id bigint, file_name varchar(255) not null, file_type varchar(255) not null, file_url varchar(255) not null, kind enum ('BIRTH_CERTIFICATE','FULL_PHOTO','GOOD_CONDUCT','NATIONAL_ID','PASSPORT','RESUME','SHOWCASE_PHOTO','VIDEO') not null, primary key (id)) engine=InnoDB;
create table notifications (is_read bit, created_at datetime(6), entity_id bigint, id bigint not null auto_increment, entity_type varchar(255), message varchar(255), recipient_staff_id bigint, type enum ('CONTRACT_EXPIRING','DEPLOYMENT','DOCUMENT_MISSING','PENDING_APPROVAL','PLACEMENT_ACTION','STATUS_CHANGE'), primary key (id)) engine=InnoDB;
create table offers (offered_salary decimal(38,2), start_date date, application_id bigint not null, created_at datetime(6) not null, expires_at datetime(6), id bigint not null auto_increment, offered_at datetime(6) not null, responded_at datetime(6), updated_at datetime(6), benefits TEXT, conditions TEXT, currency varchar(255), position_title varchar(255), rejection_reason TEXT, status enum ('ACCEPTED','EXPIRED','PENDING','REJECTED','WITHDRAWN') not null, primary key (id)) engine=InnoDB;
create table opportunities (accommodation_provided bit not null, application_deadline date, duration_months integer, filled_positions integer not null, maximum_age integer, minimum_age integer, number_of_positions integer not null, salary_maximum decimal(38,2), salary_minimum decimal(38,2), start_date date, transport_provided bit not null, contract_id bigint, created_at datetime(6), created_by bigint, employer_id bigint not null, id bigint not null auto_increment, updated_at datetime(6), benefits TEXT, country varchar(255) not null, currency varchar(255), description TEXT, job_category varchar(255), location varchar(255), required_education varchar(255), required_experience varchar(255), required_languages TEXT, required_skills TEXT, terms_and_conditions TEXT, title varchar(255) not null, working_hours varchar(255), gender_requirement enum ('FEMALE','MALE','OTHER'), status enum ('CLOSED','DRAFT','FILLED','OPEN','PAUSED','PENDING_APPROVAL') not null, primary key (id)) engine=InnoDB;
create table payment_schedules (amount decimal(38,2), due_date date, paid bit not null, contract_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, paid_at datetime(6), description varchar(255), primary key (id)) engine=InnoDB;
create table placement_checklist (completed bit not null, required bit not null, completed_at datetime(6), completed_by bigint, id bigint not null auto_increment, placement_id bigint not null, notes TEXT, item enum ('CANDIDATE_BRIEFING','EMERGENCY_CONTACT','EMPLOYER_CONFIRMATION','FLIGHT_BOOKING','MEDICAL','PASSPORT','SIGNED_CONTRACT','VISA') not null, primary key (id)) engine=InnoDB;
create table placement_documents (document_type_id bigint, file_asset_id bigint, id bigint not null auto_increment, placement_id bigint not null, uploaded_at datetime(6) not null, uploaded_by bigint, verified_at datetime(6), verified_by bigint, file_name varchar(255) not null, file_type varchar(255), file_url varchar(255) not null, doc_kind enum ('CONTRACT_SIGNED','MEDICAL_REPORT','OTHER','PASSPORT_COPY','POLICE_CLEARANCE','TICKET','VISA_COPY') not null, status varchar(30), primary key (id)) engine=InnoDB;
create table placement_history (changed_at datetime(6) not null, changed_by bigint, id bigint not null auto_increment, placement_id bigint not null, note TEXT, stage enum ('ACCEPTED','ASSIGNED','COMPLETED','CONTRACT_SIGNED','DECLINED','DEPARTED','DEPLOYED','DOCUMENTS_SUBMITTED','DOCUMENTS_VERIFIED','FLIGHT_BOOKED','MEDICAL_DONE','PRE_DEPARTURE','RENEWED','RETURNED','TERMINATED','VISA_APPLIED','VISA_APPROVED') not null, primary key (id)) engine=InnoDB;
create table placement_status_history (actor_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, placement_id bigint not null, reason TEXT, from_stage enum ('COMPLETED','CONTRACT_SIGNED','CREATED','DEPLOYED','DOCUMENTATION','MEDICAL','RETURNED','TERMINATED','TRAVEL_READY','VISA'), to_stage enum ('COMPLETED','CONTRACT_SIGNED','CREATED','DEPLOYED','DOCUMENTATION','MEDICAL','RETURNED','TERMINATED','TRAVEL_READY','VISA') not null, primary key (id)) engine=InnoDB;
create table placements (contract_end_date date, contract_start_date date, expected_end_date date, salary decimal(38,2), start_date date, accepted_offer_id bigint, applicant_id bigint, application_id bigint, assigned_at datetime(6), assigned_by bigint, contract_id bigint not null, created_at datetime(6), created_by bigint, employer_id bigint, id bigint not null auto_increment, inter_application_id bigint, opportunity_id bigint, updated_at datetime(6), candidate_type varchar(255) not null, currency varchar(255), notes TEXT, placement_number varchar(255), return_reason TEXT, termination_reason TEXT, stage varchar(40) not null, primary key (id)) engine=InnoDB;
create table recruitment_applications (applicant_id bigint not null, applied_at datetime(6) not null, assigned_recruiter_id bigint, created_at datetime(6), id bigint not null auto_increment, last_activity_at datetime(6) not null, opportunity_id bigint not null, updated_at datetime(6), rejection_details TEXT, rejection_reason enum ('CANDIDATE_WITHDREW','DOCUMENTS_INVALID','EMPLOYER_REJECTION','FAILED_INTERVIEW','FAILED_SCREENING','MISSING_QUALIFICATION','OTHER','POSITION_FILLED','SALARY_MISMATCH'), status enum ('ACCEPTED','INTERVIEW','OFFERED','PLACED','REJECTED','SCREENING','SHORTLISTED','SUBMITTED','WITHDRAWN') not null, primary key (id)) engine=InnoDB;
create table staff (id bigint not null auto_increment, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, password_hash varchar(255) not null, phone_number varchar(255), role enum ('ADMIN','RECEPTIONIST','RECRUITMENT_OFFICER','SUPER_ADMIN') not null, primary key (id)) engine=InnoDB;
create table tasks (due_date date, assigned_to bigint, completed_at datetime(6), created_at datetime(6), created_by bigint, entity_id bigint, id bigint not null auto_increment, related_applicant_id bigint, related_opportunity_id bigint, updated_at datetime(6), entity_type varchar(40), description TEXT, title varchar(255) not null, priority enum ('HIGH','LOW','MEDIUM','URGENT') not null, status enum ('CANCELLED','COMPLETED','IN_PROGRESS','OPEN') not null, primary key (id)) engine=InnoDB;
create index idx_consent_applicant on applicant_consents (applicant_id);
create index idx_consent_active on applicant_consents (applicant_id, status);
create index idx_appdoc_applicant on applicant_documents (applicant_id);
create index idx_appdoc_current on applicant_documents (applicant_id, is_current);
create index idx_appmedia_applicant on applicant_media (applicant_id);
alter table applicant_profiles add constraint UKrkdddoictlc7b0lg0urlxecv2 unique (applicant_id);
create index idx_timeline_applicant on applicant_timeline (applicant_id);
create index idx_timeline_created on applicant_timeline (created_at);
create index idx_applicant_phone on applicants (phone_number);
create index idx_applicant_number on applicants (applicant_number);
create index idx_applicant_stage on applicants (lifecycle_stage);
alter table applicants add constraint UKj6ri3wk2s9ah3l2aoyi7a89a2 unique (applicant_number);
alter table applicants add constraint UKco7alew3baakfblt96nxkosma unique (phone_number);
create index idx_campaign_member_applicant on campaign_members (applicant_id);
alter table campaign_members add constraint UKhx32kie3dqtaesjpxn2a909t5 unique (campaign_id, applicant_id);
create index idx_campaign_status on campaigns (status);
create index idx_docreq_type on document_requirements (document_type_id);
create index idx_docreq_opportunity on document_requirements (opportunity_id);
alter table document_types add constraint idx_document_type_code unique (code);
create index idx_offer_application on offers (application_id);
create index idx_offer_status on offers (status);
create index idx_opportunity_status on opportunities (status);
create index idx_opportunity_country on opportunities (country);
create index idx_opportunity_employer on opportunities (employer_id);
create index idx_pc_placement on placement_checklist (placement_id);
create index idx_pldoc_placement on placement_documents (placement_id);
create index idx_psh_placement on placement_status_history (placement_id);
create index idx_placement_applicant on placements (applicant_id);
create index idx_placement_stage on placements (stage);
create index idx_placement_opportunity on placements (opportunity_id);
alter table placements add constraint idx_placement_application unique (application_id);
alter table placements add constraint UKbc26w92e19ncdvymskq3ahj6m unique (placement_number);
create index idx_recruitment_application_applicant on recruitment_applications (applicant_id);
create index idx_recruitment_application_opportunity on recruitment_applications (opportunity_id);
create index idx_recruitment_application_status on recruitment_applications (status);
alter table staff add constraint UKpvctx4dbua9qh4p4s3gm3scrh unique (email);
create index idx_task_assigned on tasks (assigned_to);
create index idx_task_status on tasks (status);
create index idx_task_applicant on tasks (related_applicant_id);
alter table applicant_consents add constraint FKc3372jrp41c6st3iio1khbov9 foreign key (applicant_id) references applicants (id);
alter table applicant_documents add constraint FKalk36pkidjiti0lid91xbfk12 foreign key (applicant_id) references applicants (id);
alter table applicant_documents add constraint FK88a2m59wx807027l1p7f5grpy foreign key (document_type_id) references document_types (id);
alter table applicant_documents add constraint FK5vd74mun64xaof4iegfj9o97j foreign key (file_asset_id) references file_assets (id);
alter table applicant_documents add constraint FK9i7u12ddxxii4pe15eqxs62ow foreign key (verified_by) references staff (id);
alter table applicant_media add constraint FKlpni57grrs50f067cxlx3ypct foreign key (applicant_id) references applicants (id);
alter table applicant_media add constraint FK54svuxwi76r7h5shjo30j9n6g foreign key (file_asset_id) references file_assets (id);
alter table applicant_profiles add constraint FKk757pitev3req657y3tno3ow3 foreign key (applicant_id) references applicants (id);
alter table applicant_timeline add constraint FKqirq3a4y9tvj7ljdpwybshm0d foreign key (applicant_id) references applicants (id);
alter table applicant_timeline add constraint FKka5ekkdfp6q6xgutw66516l2y foreign key (performed_by) references staff (id);
alter table applicants add constraint FKr9g15g009amd6rexuikauwrts foreign key (assigned_recruiter_id) references staff (id);
alter table applicants add constraint FKa7dc9kw51a7pkkisjg2prt310 foreign key (approved_by_id) references staff (id);
alter table applicants add constraint FKq35wmmrf3bx4uf4pa8ujp418d foreign key (hired_by_id) references staff (id);
alter table applicants add constraint FKoyfkblgm7s2ctkymlvr1ihthw foreign key (vetted_by_id) references staff (id);
alter table application_languages add constraint FKnfi0fnvqicaaxp3wc9c44pvn1 foreign key (application_id) references applicants (id);
alter table audit_logs add constraint FKaa1ghgi3vkm2f9resip2o793y foreign key (changed_by) references staff (id);
alter table campaign_members add constraint FKd20iuvbl84raykxf81tsd9t0k foreign key (applicant_id) references applicants (id);
alter table campaign_members add constraint FKbfu8xwgoi73w9xmfos58e4wvy foreign key (campaign_id) references campaigns (id);
alter table campaigns add constraint FKa6cvp3pxb6hx9lyt1ej0xgy52 foreign key (created_by) references staff (id);
alter table communication_logs add constraint FK4wmi5y5bsu4knalafv52vjh5i foreign key (initiated_by) references staff (id);
alter table contract_amendments add constraint FKbj3jf8h0j0p5xf129ii07mlvv foreign key (approved_by) references staff (id);
alter table contracts add constraint FKoibglrkrgfys8bowctjdprso1 foreign key (created_by) references staff (id);
alter table contracts add constraint FK1ws7v28w1lky6j30rwa1546c4 foreign key (employer_id) references employers (id);
alter table document_requirements add constraint FKag3jh4nnelarh5mmaukeq5khy foreign key (document_type_id) references document_types (id);
alter table document_requirements add constraint FKkp8nqk5mfuo4lyhb3qhi0s7n6 foreign key (opportunity_id) references opportunities (id);
alter table file_assets add constraint FK6ba0nlvlqf5hge1d7436453tl foreign key (uploaded_by) references staff (id);
alter table int_application_languages add constraint FKr9j2d65ax6oq3ut1tp9flqocw foreign key (inter_application_id) references inter_applicants (id);
alter table inter_applicants add constraint FKh6wxay4m17ey14xpxqliu8g7r foreign key (approved_by_id) references staff (id);
alter table inter_applicants add constraint FK8c7394i1n087ps13kje2a7g9e foreign key (hired_by_id) references staff (id);
alter table inter_applicants add constraint FK23ydva6thd97riu6l9vtupvvt foreign key (vetted_by_id) references staff (id);
alter table interviews add constraint FKhdoa4unghuf3ni0ixp6pkrlmh foreign key (application_id) references recruitment_applications (id);
alter table interviews add constraint FKpsigmwcbut4mu0j46ihgg0vij foreign key (interviewer_id) references staff (id);
alter table media_files add constraint FKl9tbmw58mxnyjf0p1ev1k22ag foreign key (application_id) references applicants (id);
alter table media_files add constraint FKtbgqhq7qk0m25cp202mrgsgxm foreign key (inter_application_id) references inter_applicants (id);
alter table offers add constraint FKpalrstqfh84hppx5xx32ov6lw foreign key (application_id) references recruitment_applications (id);
alter table opportunities add constraint FKk36f7u6h7hhesps4b4tmukpee foreign key (contract_id) references contracts (id);
alter table opportunities add constraint FK8m20pqmepnoxg6ve89e5ky7jn foreign key (created_by) references staff (id);
alter table opportunities add constraint FK7qq6kehm6m73cxksfsdpbixtd foreign key (employer_id) references employers (id);
alter table placement_checklist add constraint FKjf6cnbky8exqcfeaaqw3bekk8 foreign key (completed_by) references staff (id);
alter table placement_checklist add constraint FKhgft65080e16eaervbwhy2sxl foreign key (placement_id) references placements (id);
alter table placement_documents add constraint FKil6k33h0wl3sgl4bhpa83ld67 foreign key (document_type_id) references document_types (id);
alter table placement_documents add constraint FKkswtln7oi0r1v5q0r611rgicf foreign key (file_asset_id) references file_assets (id);
alter table placement_documents add constraint FKle62fpl84ta5qygmh4m46p5ex foreign key (placement_id) references placements (id);
alter table placement_documents add constraint FK6wkfyihtcbt66kikrhlxtnenf foreign key (verified_by) references staff (id);
alter table placement_documents add constraint FKd64kr0h5bpp3f1rlqgc2eaic2 foreign key (uploaded_by) references staff (id);
alter table placement_history add constraint FKielpsbwdmtpgg3mt7ea6vpqhp foreign key (changed_by) references staff (id);
alter table placement_history add constraint FK3qh0y4rdq9b05b0m2h5wlr4bu foreign key (placement_id) references placements (id);
alter table placement_status_history add constraint FK803l8mypfccug1evknktfbayk foreign key (actor_id) references staff (id);
alter table placement_status_history add constraint FK6sv468ysv4bwroqaceenhvkqa foreign key (placement_id) references placements (id);
alter table placements add constraint FKlqwisvny3tk41j3v2ms0709hn foreign key (accepted_offer_id) references offers (id);
alter table placements add constraint FKnweueqcdnpd97q7qwqg81ygck foreign key (applicant_id) references applicants (id);
alter table placements add constraint FKerwv0ueauwpl5tjk4njc11713 foreign key (contract_id) references contracts (id);
alter table placements add constraint FKq186einru472d4paimc77d81v foreign key (created_by) references staff (id);
alter table placements add constraint FKdwx706hu5bdjlv3knu9bsarwi foreign key (employer_id) references employers (id);
alter table placements add constraint FKe4pbxwav8hl9apmkss5wq795c foreign key (opportunity_id) references opportunities (id);
alter table placements add constraint FKcg6w8y5p7f5qx857o6wbfngdt foreign key (assigned_by) references staff (id);
alter table recruitment_applications add constraint FK430yyox1ic5bud0pmeyriii0e foreign key (applicant_id) references applicants (id);
alter table recruitment_applications add constraint FKa6rgno8l5i70ljtc7ssh36gid foreign key (assigned_recruiter_id) references staff (id);
alter table recruitment_applications add constraint FK3vy470xp3p0h9q0y4c4bl8min foreign key (opportunity_id) references opportunities (id);
alter table tasks add constraint FKot16ihenjw9vs5lc09lwbssov foreign key (assigned_to) references staff (id);
alter table tasks add constraint FKhr4vg4qlux4k9pes8f9mygpdh foreign key (created_by) references staff (id);

create index idx_notifications_recipient on notifications (recipient_staff_id);
create index idx_notifications_read on notifications (is_read);
create index idx_audit_entity on audit_logs (entity_type, entity_id);
create index idx_comms_entity on communication_logs (entity_id, entity_type);
